name: Yarn
description: Sets up the Yarn, the Yarn Cache, and installs

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      shell: bash
    - name: Yarn Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-
    - run: yarn install
      shell: bash
